### ISSUE TITLE
File saving does not work perfectly on Linux

### ISSUE THREAD

**Issue by GazbonicAcid** [Bartz24/ExternalTweaker#1]
ExternalTweaker's file saving seems to be hard-coded for Windows.
Which is a serious issue for Linux users.
On linux it saves the script as "scripts\ScriptName.zs"
i DO NOT mean as "ScriptName.zs" in the "scripts" directory.
But it saves "scripts\" as part of the scripts actual file name.
And saves it in the game directory.
I must request that you change it to users like me actually get to pick the exact save location,
instead of only being able to choose the directory to save in.
[Screenshot](http://i.imgur.com/vzKknrm.png)

**Comment by Bartz24** [comment]
I'll look into it.

The Save Current Script function lets you pick the folder to save the new script in as it already has a name
It will only come up with the folder selection with new scripts the first time you save it.

If you want to pick the exact file location, use Save Current Script As

**Comment by GazbonicAcid** [comment]
Save current script as doesn't save it at all.

**Comment by Bartz24** [comment]
I'll look into that as well

**Comment by Bartz24** [comment]
When saving as, does the program give an error or does the file selection window NOT close?  It currently requires you to type the name you want into File Name (which will be automatically filled for the next release)

**Comment by GazbonicAcid** [comment]
No error what-so-ever.
The file window closes.
In all appearances ExternalTweaker appears to have saved it using "Save As"...
Until you actually go to the location you saved it.
However I think the underlying cause of these issues is thus.
I think you hard-coded folder deviations in the file-path handling to use the Windows "\\" and Linux only uses "\/" for folder deviation.
And by "deviation" I mean the character used to separate nested files/folders in the file-path.

**Comment by Bartz24** [comment]
I've fixed the seperator, but I'll continue looking into saving as...

**Comment by Bartz24** [comment]
I think I fixed the save as.

[External Tweaker Program 0.2 Test.zip](https://github.com/Bartz24/ExternalTweakerInfo/files/1099994/External.Tweaker.Program.0.2.Test.zip)

Try this version with save and save as and let me know if it works

**Comment by GazbonicAcid** [comment]
Save-as works now.
Normal saving is more broken now \([http://i.imgur.com/u2m5weX.png](http://i.imgur.com/u2m5weX.png)\)
Also a new non-problem has been found.
Intuition would say that since ExternalTweaker knows it's a string parameter,
it'll automatically surround said string parameter with double quotes \"
It does not do this however.
Also, despite this, save-as still works and is as simple as manually putting in the double quotes myself (even in the ExternalTweaker window).
[Screenies](http://imgur.com/a/nAhCR).

**Comment by Bartz24** [comment]
Strings have been fixed now

I'm not familiar with linux, so i don't know what im looking at in those 2 file windows.

**Comment by GazbonicAcid** [comment]
I had text editor's open showing what was produced from the input into ExternalTweaker....
Which you fixed.

**Comment by Bartz24** [comment]
Sorry, Not those the ones found in http://i.imgur.com/u2m5weX.png

**Comment by GazbonicAcid** [comment]
window with imgur logo, firefox web browser.
Window with book icon, ExternalTweaker.
The other two that look like file browsers,
file browsers.
The one on the left is the instance dir I selected as the location.
The one on the right is the /scripts dir within the instance dir I selected.

**Comment by Bartz24** [comment]
Oh ok

[External Tweaker Program 0.2 Test.zip](https://github.com/Bartz24/ExternalTweakerInfo/files/1100071/External.Tweaker.Program.0.2.Test.zip)

Try this one

**Comment by GazbonicAcid** [comment]
yep, fixed.
