### ISSUE TITLE
[Question/Request] Ability to export list of CraftTweaker functions

### ISSUE THREAD

**Issue by GazbonicAcid** [Bartz24/ExternalTweaker#2]
Does ExternalTweaker have the ability to export the in-game mod generated list of CraftTweaker functions ("Scripts" as the mod calls them) as plain text?
If it does not, then this is my formal request that that capability be added.

**Comment by Bartz24** [comment]
So, send the list of functions on the right of the program window to a text file?

**Comment by GazbonicAcid** [comment]
yep :smile:

**Comment by Bartz24** [comment]
added to 0.2
